"""rename department

Revision ID: 89aef2e4c7d7
Revises: 5d78c20cdfa8
Create Date: 2023-11-08 16:14:20.586760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89aef2e4c7d7'
down_revision = '5d78c20cdfa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
